# Generated by Django 3.1.5 on 2021-01-15 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='block_id',
            field=models.CharField(default='blockid', max_length=20),
        ),
    ]
