# Generated by Django 3.1.5 on 2021-01-15 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_block_block_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='block_id',
            field=models.CharField(default='default', max_length=20),
        ),
    ]
